import 'package:ethical_scanner/data/data_sources/local/local_data_source_impl.dart';
import 'package:ethical_scanner/res/enums/settings.dart';
import 'package:mockito/mockito.dart';

import 'mock_shared_preferences.dart';

class MockLocalDataSourceImpl extends Mock implements LocalDataSourceImpl {
  factory MockLocalDataSourceImpl() => _instance;

  MockLocalDataSourceImpl._internal();

  static final MockLocalDataSourceImpl _instance =
      MockLocalDataSourceImpl._internal();
  late final MockSharedPreferences _sharedPrefs = MockSharedPreferences();

  @override
  Future<void> init() {
    return Future<void>.value();
  }

  /// Function to retrieve the country from barcode.
  ///
  /// References:
  /// https://www.barcodestalk.com/learn-about-barcodes/resources/barcode-country-codes
  /// https://internationalbarcodes.com/barcode-country-codes/
  /// https://en.wikipedia.org/wiki/List_of_GS1_country_codes
  /// https://en.wikipedia.org/wiki/ISO_3166-1_numeric
  @override
  String getGs1CountryFromBarcode(String barcode) {
    // List of countries with corresponding barcode prefixes
    final Map<String, String> countryCodeMap = <String, String>{
      '0': 'USA / Canada',
      '000': 'United States and Canada',
      '001': 'United States',
      '002': 'United States',
      '003': 'United States',
      // ISO 3166-1 numeric for Afghanistan and GS1 USA country code
      '004': 'USA(GS1)/Afghanistan(ISO 3166-1)',
      '005': 'United States',
      '006': 'United States',
      '007': 'United States',
      // ISO 3166-1 numeric for Albania and GS1 USA country code
      '008': 'USA(GS1)/Albania(ISO 3166-1)',
      '009': 'United States',
      '010': 'United States',
      '011': 'United States',
      '012': 'USA(GS1)/Algeria(ISO 3166-1)',
      '013': 'United States',
      '014': 'United States',
      '015': 'United States',
      '016': 'United States',
      '017': 'United States',
      '018': 'United States',
      '019': 'United States and Canada',
      '020': 'Andorra(ISO 3166-1)',
      '024': 'Angola(ISO 3166-1)',
      '028': 'Antigua and Barbuda(ISO 3166-1)',
      '030': 'United States',
      '031': 'United States',
      '032': 'USA(GS1)/Argentina(ISO 3166-1)',
      '033': 'United States',
      '034': 'United States',
      '035': 'United States',
      '036': 'USA(GS1)/Australia(ISO 3166-1)',
      '037': 'United States',
      '038': 'United States',
      '039': 'United States',
      '040': 'Austria(ISO 3166-1)',
      '044': 'Bahamas(ISO 3166-1)',
      '048': 'Bahrain(ISO 3166-1)',
      '050': 'US(GS1)/Bangladesh(ISO 3166-1)',
      '051': 'US(GS1)/Armenia(ISO 3166-1)',
      '052': 'US(GS1)/Barbados(ISO 3166-1)',
      '056': 'US(GS1)/Belgium(ISO 3166-1)',
      // 057 is EAN-13 barcode prefix for the United States
      '057': 'United States',
      '060': 'United States and Canada',
      '061': 'United States',
      '062': 'United States',
      '063': 'United States',
      '064': 'United States',
      '065': 'United States',
      '066': 'United States',
      '067': 'United States',
      '068': 'United States',
      '069': 'United States',
      '070': 'United States',
      '071': 'United States',
      '072': 'United States',
      '073': 'United States',
      '074': 'United States',
      '075': 'United States',
      '076': 'United States',
      '077': 'United States',
      '078': 'United States',
      '079': 'United States',
      '080': 'United States',
      '081': 'United States',
      '082': 'United States',
      '083': 'United States',
      '084': 'United States',
      '085': 'United States',
      '086': 'United States',
      '087': 'United States',
      '088': 'United States',
      '089': 'United States',
      '090': 'United States',
      '091': 'United States',
      '092': 'United States',
      '093': 'United States',
      '094': 'United States',
      '095': 'United States',
      '096': 'United States',
      '097': 'United States',
      '098': 'United States',
      '099': 'United States and Canada',
      '1': 'USA',
      '100': 'United States',
      '101': 'United States',
      '102': 'United States',
      '103': 'United States',
      '104': 'United States',
      '105': 'United States',
      '106': 'United States',
      '107': 'United States',
      '108': 'United States',
      '109': 'United States',
      '110': 'United States',
      '111': 'United States',
      '112': 'United States',
      '113': 'United States',
      '114': 'United States',
      '115': 'United States',
      '116': 'United States',
      '117': 'United States',
      '118': 'United States',
      '119': 'United States',
      '120': 'United States',
      '121': 'United States',
      '122': 'United States',
      '123': 'United States',
      '124': 'Canada',
      '125': 'United States',
      '126': 'United States',
      '127': 'United States',
      '128': 'United States',
      '129': 'United States',
      '130': 'United States',
      '131': 'United States',
      '132': 'United States',
      '133': 'United States',
      '134': 'United States',
      '135': 'United States',
      '136': 'United States',
      '137': 'United States',
      '138': 'United States',
      '139': 'United States',
      '140': 'Central African Republic',
      '144': 'Sri Lanka',
      '148': 'Chad',
      '152': 'Chile',
      '156': 'China',
      '170': 'Colombia',
      '174': 'Comoros',
      '178': 'Congo (Congo-Brazzaville)',
      '180': 'Congo (Congo-Kinshasa)',
      '184': 'Cook Islands',
      '188': 'Costa Rica',
      '191': 'Croatia',
      '192': 'Cuba',
      '196': 'Cyprus',
      '203': 'Czechia (Czech Republic)',
      '204': 'Benin',
      '208': 'Denmark',
      '212': 'Dominica',
      '214': 'Dominican Republic',
      '218': 'Ecuador',
      '222': 'El Salvador',
      '226': 'Equatorial Guinea',
      '231': 'Ethiopia',
      '232': 'Eritrea',
      '233': 'Estonia',
      '234': 'Faroe Islands',
      '238': 'Falkland Islands (Malvinas)',
      '242': 'Fiji',
      '246': 'Finland',
      '250': 'France',
      '254': 'French Guiana',
      '258': 'French Polynesia',
      '260': 'French Southern Territories',
      '262': 'Djibouti',
      '266': 'Gabon',
      '268': 'Georgia',
      '270': 'Gambia',
      '275': 'Palestine',
      '276': 'Germany',
      '288': 'Ghana',
      '292': 'Gibraltar',
      '296': 'Kiribati',
      '30': 'France & Monaco',
      '300': 'France and Monaco',
      '301': 'France and Monaco',
      '302': 'France and Monaco',
      '303': 'France and Monaco',
      '304': 'France and Monaco',
      '305': 'France and Monaco',
      '306': 'France and Monaco',
      '307': 'France and Monaco',
      '308': 'France and Monaco',
      '309': 'France and Monaco',
      '31': 'France & Monaco',
      '310': 'France and Monaco',
      '311': 'France and Monaco',
      '312': 'France and Monaco',
      '313': 'France and Monaco',
      '314': 'France and Monaco',
      '315': 'France and Monaco',
      '316': 'France and Monaco',
      '317': 'France and Monaco',
      '318': 'France and Monaco',
      '319': 'France and Monaco',
      '32': 'France & Monaco',
      '320': 'France and Monaco',
      '321': 'France and Monaco',
      '322': 'France and Monaco',
      '323': 'France and Monaco',
      '324': 'France and Monaco',
      '325': 'France and Monaco',
      '326': 'France and Monaco',
      '327': 'France and Monaco',
      '328': 'France and Monaco',
      '329': 'France and Monaco',
      '33': 'France & Monaco',
      '330': 'France and Monaco',
      '331': 'France and Monaco',
      '332': 'France and Monaco',
      '333': 'France and Monaco',
      '334': 'France and Monaco',
      '335': 'France and Monaco',
      '336': 'France and Monaco',
      '337': 'France and Monaco',
      '338': 'France and Monaco',
      '339': 'France and Monaco',
      '34': 'France & Monaco',
      '340': 'France and Monaco',
      '341': 'France and Monaco',
      '342': 'France and Monaco',
      '343': 'France and Monaco',
      '344': 'France and Monaco',
      '345': 'France and Monaco',
      '346': 'France and Monaco',
      '347': 'France and Monaco',
      '348': 'France and Monaco',
      '349': 'France and Monaco',
      '35': 'France & Monaco',
      '350': 'France and Monaco',
      '351': 'France and Monaco',
      '352': 'France and Monaco',
      '353': 'France and Monaco',
      '354': 'France and Monaco',
      '355': 'France and Monaco',
      '356': 'France and Monaco',
      '357': 'France and Monaco',
      '358': 'France and Monaco',
      '359': 'France and Monaco',
      '36': 'France & Monaco',
      '360': 'France and Monaco',
      '361': 'France and Monaco',
      '362': 'France and Monaco',
      '363': 'France and Monaco',
      '364': 'France and Monaco',
      '365': 'France and Monaco',
      '366': 'France and Monaco',
      '367': 'France and Monaco',
      '368': 'France and Monaco',
      '369': 'France and Monaco',
      '37': 'France & Monaco',
      '370': 'France and Monaco',
      // This is the prefix to the barcode of Toronto public library
      '371': 'Canada',
      '372': 'France and Monaco',
      '373': 'France and Monaco',
      '374': 'France and Monaco',
      '375': 'France and Monaco',
      '376': 'France and Monaco',
      '377': 'France and Monaco',
      '378': 'France and Monaco',
      '379': 'France and Monaco',
      '380': 'Bulgaria',
      '383': 'Slovenia',
      '384': 'Cote d\'Ivoire (Ivory Coast)',
      '385': 'Croatia',
      '387': 'Bosnia and Herzegovina',
      '388': 'Jamaica',
      '389': 'Montenegro',
      '390': 'Republic of Kosovo',
      '392': 'Japan',
      '398': 'Kazakhstan',
      '40': 'Germany',
      '400': 'Germany',
      '401': 'Germany',
      '402': 'Germany',
      '403': 'Germany',
      '404': 'Germany',
      '405': 'Germany',
      '406': 'Germany',
      '407': 'Germany',
      '408': 'Germany',
      '409': 'Germany',
      '41': 'Germany',
      '410': 'Germany',
      '411': 'Germany',
      '412': 'Germany',
      '413': 'Germany',
      '414': 'Germany',
      '415': 'Germany',
      '416': 'Germany',
      '417': 'Germany',
      '418': 'Germany',
      '419': 'Germany',
      '42': 'Germany',
      '420': 'Germany',
      '421': 'Germany',
      '422': 'Germany',
      '423': 'Germany',
      '424': 'Germany',
      '425': 'Germany',
      '426': 'Germany',
      '427': 'Germany',
      '428': 'Germany',
      '429': 'Germany',
      '43': 'Germany',
      '430': 'Germany',
      '431': 'Germany',
      '432': 'Germany',
      '433': 'Germany',
      '434': 'Germany',
      '435': 'Germany',
      '436': 'Germany',
      '437': 'Germany',
      '438': 'Germany',
      '439': 'Germany',
      '44': 'Germany',
      '440': 'Germany',
      '442': 'Luxembourg',
      '446': 'Macao',
      '45': 'Japan',
      '450': 'Japan',
      '451': 'Japan',
      '452': 'Japan',
      '453': 'Japan',
      '454': 'Japan',
      '455': 'Japan',
      '456': 'Japan',
      '457': 'Japan',
      '458': 'Japan',
      '459': 'Japan',
      '46': 'Russia',
      '460': 'Russia',
      '461': 'Russia',
      '462': 'Russia',
      '463': 'Russia',
      '464': 'Russia',
      '465': 'Russia',
      '466': 'Russia',
      '467': 'Russia',
      '468': 'Russia',
      '469': 'Russia',
      '470': 'Kyrgyzstan',
      '471': 'Taiwan',
      '474': 'Estonia',
      '475': 'Latvia',
      '476': 'Azerbaijan',
      '477': 'Lithuania',
      '478': 'Uzbekistan',
      '479': 'Sri Lanka',
      '480': 'Philippines',
      '481': 'Belarus',
      // 482 is a EAN-13 barcode prefix for Ukraine
      '482': 'Ukraine',
      '483': 'Turkmenistan',
      // 484 is ISO 3166-1 numeric code for Mexico and EAN-13 barcode prefix for
      // Moldova
      '484': 'Mexico or Moldova',
      '485': 'Armenia',
      '486': 'Georgia',
      '487': 'Kazakhstan',
      '488': 'Tajikistan',
      '489': 'Hong Kong',
      '49': 'Japan',
      '490': 'Japan',
      '491': 'Japan',
      '492': 'Japan',
      '493': 'Japan',
      '494': 'Japan',
      '495': 'Japan',
      '496': 'Japan',
      '497': 'Japan',
      '498': 'Japan',
      '499': 'Japan',
      '50': 'United Kingdom',
      '500': 'United Kingdom',
      '501': 'United Kingdom',
      '502': 'United Kingdom',
      '503': 'United Kingdom',
      '504': 'United Kingdom',
      '505': 'United Kingdom',
      '506': 'United Kingdom',
      '507': 'United Kingdom',
      '508': 'United Kingdom',
      '509': 'United Kingdom',
      '512': 'Oman',
      '516': 'Namibia',
      '520': 'Greece',
      '521': 'Greece',
      '524': 'Nepal',
      '528': 'Lebanon',
      '529': 'Cyprus',
      '530': 'Albania',
      '531': 'North Macedonia',
      '533': 'Aruba',
      '534': 'Sint Maarten (Dutch part)',
      '535': 'Malta',
      '539': 'Ireland',
      '540': 'Belgium and Luxembourg',
      '541': 'Belgium and Luxembourg',
      '542': 'Belgium and Luxembourg',
      '543': 'Belgium and Luxembourg',
      '544': 'Belgium and Luxembourg',
      '545': 'Belgium and Luxembourg',
      '546': 'Belgium and Luxembourg',
      '547': 'Belgium and Luxembourg',
      '548': 'Belgium and Luxembourg',
      '549': 'Belgium and Luxembourg',
      '554': 'New Zealand',
      '558': 'Nicaragua',
      '560': 'Portugal',
      '562': 'Niger',
      '566': 'Nigeria',
      '569': 'Iceland',
      '570': 'Denmark, Faroe Islands and Greenland',
      '571': 'Denmark, Faroe Islands and Greenland',
      '572': 'Denmark, Faroe Islands and Greenland',
      '573': 'Denmark, Faroe Islands and Greenland',
      '574': 'Denmark, Faroe Islands and Greenland',
      '575': 'Denmark, Faroe Islands and Greenland',
      '576': 'Denmark, Faroe Islands and Greenland',
      '577': 'Denmark, Faroe Islands and Greenland',
      '578': 'Norway',
      '579': 'Denmark, Faroe Islands and Greenland',
      '580': 'Northern Mariana Islands',
      '581': 'United States Minor Outlying Islands',
      '583': 'Micronesia',
      '584': 'Marshall Islands',
      '585': 'Palau',
      '586': 'Pakistan',
      '590': 'Poland',
      '591': 'Panama',
      '594': 'Romania',
      '598': 'Papua New Guinea',
      '599': 'Hungary',
      '600': 'South Africa',
      '601': 'South Africa',
      '603': 'Ghana',
      '604': 'Senegal',
      '607': 'Oman',
      '608': 'Bahrain',
      '609': 'Mauritius',
      '611': 'Morocco',
      '612': 'Pitcairn',
      '613': 'Algeria',
      '615': 'Nigeria',
      '616': 'Kenya',
      '617': 'Cameroon',
      '618': 'Ivory Coast',
      '619': 'Tunisia',
      '620': 'Tanzania',
      '621': 'Syria',
      '622': 'Egypt',
      '624': 'Libya',
      '625': 'Jordan',
      '626': 'Iran',
      '627': 'Kuwait',
      // “628” is the GS1 barcode of Saudi Arabia.
      '628': 'Saudi Arabia',
      '629': 'United Arab Emirates',
      '630': 'Qatar',
      '631': 'Namibia',
      '634': 'Reunion',
      '64': 'Finland',
      '640': 'Finland',
      '641': 'Finland',
      '642': 'Finland',
      '643': 'Finland',
      '644': 'Finland',
      '645': 'Finland',
      '646': 'Finland',
      '647': 'Finland',
      '648': 'Finland',
      '649': 'Finland',
      '652': 'Saint Barthelemy',
      '654': 'Saint Helena',
      '659': 'Saint Kitts and Nevis',
      '662': 'Anguilla',
      '663': 'Saint Lucia',
      '666': 'Saint Martin',
      '670': 'Saint Pierre and Miquelon',
      '674': 'Saint Vincent and the Grenadines',
      '678': 'San Marino',
      '680': 'China',
      '681': 'China',
      '682': 'Sao Tome and Principe',
      '686': 'Saudi Arabia',
      '688': 'Senegal',
      '69': 'China',
      '690': 'China',
      '691': 'China',
      '692': 'China',
      '693': 'China',
      '694': 'China',
      '695': 'China',
      '696': 'China',
      '697': 'China',
      '698': 'China',
      '699': 'China',
      '70': 'Norway',
      '700': 'Norway',
      '701': 'Norway',
      '702': 'Norway',
      '703': 'Norway',
      '704': 'Norway',
      '705': 'Norway',
      '706': 'Norway',
      '707': 'Norway',
      '708': 'Norway',
      '709': 'Norway',
      '710': 'South Africa',
      '716': 'Zimbabwe',
      '724': 'Spain',
      '728': 'South Sudan',
      '729': 'Israel',
      '73': 'Sweden',
      '730': 'Sweden',
      '731': 'Sweden',
      '732': 'Sweden',
      '733': 'Sweden',
      '734': 'Sweden',
      '735': 'Sweden',
      '736': 'Sweden',
      '737': 'Sweden',
      '738': 'Sweden',
      '739': 'Sweden',
      '740': 'Guatemala',
      '741': 'El Salvador',
      '742': 'Honduras',
      '743': 'Nicaragua',
      '744': 'Costa Rica',
      '745': 'Panama',
      '746': 'Dominican Republic',
      '748': 'Eswatini',
      '750': 'Mexico',
      '752': 'Sweden',
      '754': 'Canada',
      '755': 'Canada',
      '756': 'Switzerland',
      '759': 'Venezuela or Mexico',
      // The prefix "76" indicates that it is registered with the UCC
      // (Uniform Code Council) system, which is commonly used in the USA.
      '76': 'United States',
      '760': 'Switzerland and Liechtenstein',
      '761': 'Switzerland and Liechtenstein',
      '762': 'Switzerland and Liechtenstein',
      '763': 'Switzerland and Liechtenstein',
      '764': 'Switzerland and Liechtenstein',
      '765': 'Switzerland and Liechtenstein',
      '766': 'Switzerland and Liechtenstein',
      '767': 'Switzerland and Liechtenstein',
      '768': 'Switzerland and Liechtenstein',
      '769': 'Switzerland and Liechtenstein',
      '770': 'Colombia',
      '771': 'Colombia',
      '772': 'Tokelau',
      '773': 'Uruguay',
      '775': 'Peru',
      '776': 'Tonga',
      '777': 'Bolivia',
      '778': 'Argentina',
      '779': 'Argentina',
      '780': 'Chile',
      '784': 'Paraguay',
      '786': 'Ecuador',
      '788': 'Tunisia',
      '789': 'Brazil',
      '790': 'Brazil',
      '792': 'Turkey',
      '795': 'Turkmenistan',
      '796': 'Turks and Caicos Islands',
      '798': 'Tuvalu',
      '800': 'Italy, San Marino and Vatican City',
      '801': 'Italy, San Marino and Vatican City',
      '802': 'Italy, San Marino and Vatican City',
      '803': 'Italy, San Marino and Vatican City',
      '804': 'Italy, San Marino and Vatican City',
      '805': 'Italy, San Marino and Vatican City',
      '806': 'Italy, San Marino and Vatican City',
      '807': 'Italy, San Marino and Vatican City',
      '808': 'Italy, San Marino and Vatican City',
      '809': 'Italy, San Marino and Vatican City',
      '810': 'Italy, San Marino and Vatican City',
      '811': 'Italy, San Marino and Vatican City',
      '812': 'Italy, San Marino and Vatican City',
      '813': 'Italy, San Marino and Vatican City',
      '814': 'Italy, San Marino and Vatican City',
      '815': 'Italy, San Marino and Vatican City',
      '816': 'Italy, San Marino and Vatican City',
      '817': 'Italy, San Marino and Vatican City',
      '818': 'Italy, San Marino and Vatican City',
      '819': 'Italy, San Marino and Vatican City',
      '820': 'Italy, San Marino and Vatican City',
      '821': 'Italy, San Marino and Vatican City',
      '822': 'Italy, San Marino and Vatican City',
      '823': 'Italy, San Marino and Vatican City',
      '824': 'Italy, San Marino and Vatican City',
      '825': 'Italy, San Marino and Vatican City',
      '826': 'Italy, San Marino and Vatican City',
      '827': 'Italy, San Marino and Vatican City',
      '828': 'Italy, San Marino and Vatican City',
      '829': 'Italy, San Marino and Vatican City',
      '830': 'Italy, San Marino and Vatican City',
      '831': 'Italy, San Marino and Vatican City',
      '832': 'Italy, San Marino and Vatican City',
      '833': 'Italy, San Marino and Vatican City',
      '834': 'Italy, San Marino and Vatican City',
      '835': 'Italy, San Marino and Vatican City',
      '836': 'Italy, San Marino and Vatican City',
      '837': 'Italy, San Marino and Vatican City',
      '838': 'Italy, San Marino and Vatican City',
      '839': 'Italy, San Marino and Vatican City',
      // 840 is ISO 3166-1 numeric code for the United States or GS1 code for
      // Spain and Andorra
      '840': 'Spain and Andorra',
      '841': 'Spain and Andorra',
      '842': 'Spain and Andorra',
      '843': 'Spain and Andorra',
      '844': 'Spain and Andorra',
      '845': 'Spain and Andorra',
      '846': 'Spain and Andorra',
      '847': 'Spain and Andorra',
      '848': 'Spain and Andorra',
      '849': 'Spain and Andorra',
      '850': 'Cuba',
      '854': 'Burkina Faso',
      '858': 'Slovakia',
      '859': 'Czech Republic',
      '860': 'Serbia',
      '862': 'Venezuela',
      '865': 'Mongolia',
      '867': 'North Korea',
      '868': 'Turkey',
      '869': 'Turkey',
      '870': 'Netherlands',
      '871': 'Netherlands',
      '872': 'Netherlands',
      '873': 'Netherlands',
      '874': 'Netherlands',
      '875': 'Netherlands',
      '876': 'Netherlands',
      '877': 'Netherlands',
      '878': 'Netherlands',
      '879': 'Netherlands',
      '880': 'South Korea',
      '881': 'South Korea',
      '882': 'Samoa',
      '883': 'Myanmar',
      '884': 'Cambodia',
      '885': 'Thailand',
      '887': 'Yemen',
      '888': 'Singapore',
      '890': 'India',
      '893': 'Vietnam',
      '894': 'Zambia',
      '896': 'Pakistan',
      '899': 'Indonesia',
      '90': 'Austria',
      '900': 'Austria',
      '901': 'Austria',
      '902': 'Austria',
      '903': 'Austria',
      '904': 'Austria',
      '905': 'Austria',
      '906': 'Austria',
      '907': 'Austria',
      '908': 'Austria',
      '909': 'Austria',
      '91': 'Austria',
      '910': 'Austria',
      '911': 'Austria',
      '912': 'Austria',
      '913': 'Austria',
      '914': 'Austria',
      '915': 'Austria',
      '916': 'Austria',
      '917': 'Austria',
      '918': 'Austria',
      '919': 'Austria',
      '93': 'Australia',
      '930': 'Australia',
      '931': 'Australia',
      '932': 'Australia',
      '933': 'Australia',
      '934': 'Australia',
      '935': 'Australia',
      '936': 'Australia',
      '937': 'Australia',
      '938': 'Australia',
      '939': 'Australia',
      '94': 'New Zealand',
      '940': 'New Zealand',
      '941': 'New Zealand',
      '942': 'New Zealand',
      '943': 'New Zealand',
      '944': 'New Zealand',
      '945': 'New Zealand',
      '946': 'New Zealand',
      '947': 'New Zealand',
      '948': 'New Zealand',
      '949': 'New Zealand',
      '955': 'Malaysia',
      '958': 'Macau',
    };

    final String prefix = barcode.substring(0, 3);

    // Check barcode format and retrieve country
    return countryCodeMap[prefix] ??
        countryCodeMap[barcode.substring(0, 2)] ??
        countryCodeMap[barcode.substring(0, 1)] ??
        '';
  }

  @override
  String getReportedOriginFromBarcode(String barcode) {
    const Map<String, String> reportedOriginMap = <String, String>{
      '057': 'China',
      '060': 'Switzerland',
      '061': 'Greece',
      '066': 'Colombia',
      '191': 'China',
      '194': 'Bangladesh',
      '195': 'China',
      '197': 'Cambodia, Bangladesh, Vietnam',
      '198': 'China',
      '336': 'China',
      '360': 'United States',
      '620': 'China',
      '626': 'Canada',
      '627': 'China',
      '632': 'China',
      '655': 'China',
      '665': 'China',
      '667': 'Vietnam',
      '773': 'China',
      '837': 'China',
      '850': 'United States',
      '856': 'Colombia',
      '874': 'Canada',
    };
    return reportedOriginMap[barcode.substring(0, 3)] ?? '';
  }

  @override
  bool isEnglishBook(String barcode) {
    final List<int> digits = barcode.codeUnits
        .where((int char) => char >= 48 && char <= 57)
        .map((int char) => char - 48)
        .toList();

    if (digits.length != 13) {
      return false;
    }

    // Check if it starts with "978" (common Book-land prefix)
    if (digits.sublist(0, 3).join() != '978') {
      return false;
    }
    return true;
  }

  @override
  Future<bool> savePrecipitationState(bool isPrecipitationFalling) =>
      _sharedPrefs.setBool(
        Settings.precipitationFalling.key,
        isPrecipitationFalling,
      );

  @override
  bool getPrecipitationState() =>
      _sharedPrefs.getBool(Settings.precipitationFalling.key) ?? true;

  @override
  Future<bool> saveSoundPreference(bool isSoundOn) =>
      _sharedPrefs.setBool(Settings.sound.key, isSoundOn);

  @override
  bool getSoundPreference() =>
      _sharedPrefs.getBool(Settings.sound.key) ?? false;

  @override
  String getLanguageIsoCode() => 'mock';

  @override
  Future<bool> saveLanguageIsoCode(String languageIsoCode) =>
      _sharedPrefs.setString(Settings.languageIsoCode.key, languageIsoCode);
}
