name: entities
description: An Entity is an object within our computer system that embodies a small set of
  critical business rules operating on Critical Business Data.
version: 1.0.0
repository: https://github.com/Turskyi/ethical_scanner/tree/master/components/core/entities

environment:
  sdk: '>=3.2.3 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
