name: use_cases
description: A use case is a description of the way that an automated system
  is used. It specifies the input to be provided by the user, the output to be
  returned to the user, and the processing steps involved in producing that
  output. A use case describes application-specific business rules.
version: 0.1.0
# This prevents the package from being accidentally published to pub.dev using pub publish. This is
# preferred for private packages.
publish_to: none
repository: https://github.com/Turskyi/ethical_scanner/tree/master/components/domain/use_cases
issue_tracker: https://github.com/users/Turskyi/projects/10/views/1?layout=board

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  entities:
    path: ../entities

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
