name: use_cases
description: A use case is a description of the way that an automated system is used. It specifies
  the input to be provided by the user, the output to be returned to the user, and the processing
  steps involved in producing that output. A use case describes application-specific business rules.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  entities:
    path: ../entities

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
