// Mocks generated by Mockito 5.4.6 from annotations
// in interface_adapters/test/src/ui/modules/ingredients_editor/ingredients_editor_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:entities/entities.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:use_cases/use_cases.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExtractIngredientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtractIngredientsUseCase extends _i1.Mock
    implements _i2.ExtractIngredientsUseCase {
  MockExtractIngredientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call([
    _i4.ProductPhoto? productPhoto = const _i4.ProductPhoto(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productPhoto]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#call, [productPhoto]),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [SaveIngredientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveIngredientsUseCase extends _i1.Mock
    implements _i2.SaveIngredientsUseCase {
  MockSaveIngredientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call([
    _i2.SaveIngredientsParams? params = const _i2.SaveIngredientsParams(
      barcode: '',
      ingredientsText: '',
      language: _i4.Language.en,
    ),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SaveLanguageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLanguageUseCase extends _i1.Mock
    implements _i2.SaveLanguageUseCase {
  MockSaveLanguageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> call([String? languageIsoCode = 'en']) =>
      (super.noSuchMethod(
            Invocation.method(#call, [languageIsoCode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [GetLanguageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLanguageUseCase extends _i1.Mock
    implements _i2.GetLanguageUseCase {
  MockGetLanguageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Language call([Object? _0]) =>
      (super.noSuchMethod(
            Invocation.method(#call, [_0]),
            returnValue: _i4.Language.en,
          )
          as _i4.Language);
}
