name: Code Quality

on: [ push ]

jobs:
  check_lint_errors:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Display files in root
        run: ls -a

      - name: Navigate to interface_adapters folder
        run: cd components/interface_adapters

      - name: Display files after navigation
        run: ls -a

      - name: Write interface_adapters .env file
        run: |
          echo $ENV | base64 -d > .env
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Display files in interface adapters
        run: ls -a

      - name: Write interface_adapters env.g.dart file
        run: |
          dart run build_runner build --delete-conflicting-outputs
        shell: bash

      - name: Display files in current folder
        run: ls -a

      - name: Navigate to env folder
        run: cd lib/src/env

      - name: Display files in interface adapters env directory
        run: ls -a

      - name: Return to the root directory
        run: cd ../../../../..

      - name: Get packages
        run: flutter pub get

      - name: Check lint errors
        run: flutter analyze .

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 35
