name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - dev

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Write key.properties file
        run: |
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
        shell: bash
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Create keystore folder
        run: mkdir -p android/keystore

      - name: Write ethical_scanner_release.keystore file
        run: |
          echo $RELEASE_KEYSTORE | base64 --decode > android/keystore/ethical_scanner_release.keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}

      - name: Write ethical_scanner_debug.keystore file
        run: |
          echo $DEBUG_KEYSTORE | base64 -d > android/keystore/ethical_scanner_debug.keystore
        shell: bash
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Eclipse Temurin https://adoptium.net/
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: build/app/outputs/flutter-apk/app-release.apk

  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-build

      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          releaseNotes: "Ethical Scanner Android Application Build"
          file: build/app/outputs/flutter-apk/app-release.apk
